apiVersion: v1
kind: Namespace
metadata:
  name: stairwell
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stairwell
  name: entrypoint-deployment
spec:
  selector:
    matchLabels:
      app: entrypoint
  template:
    metadata:
      labels:
        app: entrypoint
    spec:
      containers:
        - name: entrypoint-container
          # It's totally fine to store the image in a container registry.
          # If so, you'll probably want to change the image and pull policy.
          image: stairwell/entrypoint
          imagePullPolicy: Never
          args:
            - --uri=https://stairwell.com/robots.txt # TODO(candidate): Change this.
          ports:
            - protocol: TCP
              containerPort: 8080
              name: http-server
---
apiVersion: v1
kind: Service
metadata:
  namespace: stairwell
  name: entrypoint-service
# With this service definition, you'll be able to reach the server from your local machine.
# However, you may want to set up some sort of ingress to expose it to the public.
spec:
  type: NodePort
  selector:
    app: entrypoint
  ports:
    - protocol: TCP
      name: http-server
      targetPort: http-server
      port: 42069
